import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E8EAED",
    padding: 30,
    alignItems: "center",
  },
  btnSort: { flex: 0.07 },
  containerFilters: {
    flex: 0.07,
    alignContent: "center",
  },
  containerFl: {
    flex: 1,
    justifyContent: "center",
    alignContent: "center",
  },
  chipFilters: {
    marginHorizontal: 5,
  },
  btnFilters: {
    backgroundColor: "white",
  },
  txtSearchDefault: {
    width: "100%",
    backgroundColor: "#FFF",
    borderRadius: 40,
    marginTop: 20,
    padding: 10,
    paddingHorizontal: 15,
    justifyContent: "center",
    alignItems: "center",
    color: "#C7C7CD",
    fontSize: 15,
  },

  txtSearch: {
    width: "100%",
    backgroundColor: "#FFF",
    borderRadius: 40,
    marginTop: 20,
    padding: 10,
    paddingHorizontal: 15,
    justifyContent: "flex-start",
    alignItems: "center",
    color: "#000000",
    fontSize: 15,
  },

  viewSearchMode: {
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  svResults: {
    marginTop: 20,
    borderRadius: 10,
    backgroundColor: "#fff",
  },
  touOpSearchMode: {
    padding: 5,
    width: "20%",
    borderColor: "#587F8E",
    borderWidth: 1.5,
    borderRadius: 40,
  },
  touOpSearchModePressed: {
    padding: 6.5,
    width: "20%",
    backgroundColor: "#305f72",
    borderRadius: 30,
  },
  txtSearchMode: {
    alignSelf: "center",
    color: "#000",
    fontWeight: "bold",
    fontSize: 12,
    opacity: 1,
    fontSize: 15,
  },
  txtSearchModePressed: {
    alignSelf: "center",
    color: "#fff",
    fontWeight: "bold",
    fontSize: 12,
    opacity: 1,
    fontSize: 15,
  },
  containerWhite: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 30,
  },
  txtinpSearchBorder: {
    width: "100%",
    backgroundColor: "#FFF",
    borderRadius: 40,
    marginTop: 20,
    padding: 6,
    borderBottomColor: "#ccc",
    borderBottomWidth: 1,
    borderTopColor: "#ccc",
    borderTopWidth: 1,
    borderLeftColor: "#ccc",
    borderLeftWidth: 1,
    borderRightColor: "#ccc",
    borderRightWidth: 1,
    paddingHorizontal: 15,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    fontSize: 15,
  },
  containerListItems: {
    backgroundColor: "#FFF",
    paddingHorizontal: 10,
    paddingVertical: 15,
  },

  containerCurrentLocation: {
    backgroundColor: "#FFF",
    paddingHorizontal: 10,
    paddingVertical: 15,
  },
  txtListItemsBuilding: {
    fontWeight: "bold",
    fontSize: 18,
  },
  txtListItemsAddress: {
    fontSize: 15,
  },
  containerCurrentLocation: {
    backgroundColor: "#FFF",
    paddingHorizontal: 10,
    paddingVertical: 15,
  },
  containerFlatList: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    marginTop: 5,
  },

  containerFlatListItems: {
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  txtNoCarparks: {
    fontWeight: "bold",
    fontSize: 18,
    paddingHorizontal: 30,
  },
  txtCPSummary: {
    fontWeight: "bold",
    fontSize: 18,
    textAlign: "center",
  },
  containerOTP: {
    flexDirection: "row",
    alignItems: "center",
    padding: 50,
    justifyContent: "space-around",
    bottom: "10%",
    padding: 10,
  },
  txtInpOTP: {
    borderBottomColor: "black",
    borderBottomWidth: 1,
    marginHorizontal: 10,
    textAlign: "center",
    fontSize: 14,
  },
  logo: {
    height: "65%",
    top: "-10%",
  },
  containerLogo: {
    justifyContent: "center",
    alignItems: "center",
  },
  txtInpPhoneNumber: {
    backgroundColor: "#FAFAFA",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    fontSize: 14,
    left: 5,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderRadius: 5,
    borderColor: "#F3F3F3",
    width: "85%",
    bottom: "10%",
    padding: 10,
  },
  btnContinue: {
    alignItems: "center",
    justifyContent: "center",
  },
  txtContinue: {
    color: "#4f8BFF",
    alignContent: "center",
    justifyContent: "center",
    fontSize: 18,
    bottom: "5%",
  },
});

export default styles;
